version: '3.9'

services:
  go-server:
    container_name: go-server
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - pg_db
    environment:
      DSN_LOCAL: "postgres://greenlight:pa55word@localhost:5432/greenlight?sslmode=disable"
      DSN: "host=pg_db port=5432 user=greenlight password=pa55word dbname=greenlight sslmode=disable"
  pg_db:
    container_name: pg_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
